/*
 * Copyright (C) 2021 eccentric_nz
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package me.eccentric_nz.tardisschematicviewer;

import java.awt.*;

/**
 * An enum of all materials accepted by the official server and client
 */
public enum Material {

    ACACIA_BUTTON(BlockShape.SMALL, Color.getHSBColor(0.01f, 0.52f, 0.59f)),
    ACACIA_DOOR(BlockShape.DOOR, Color.getHSBColor(0.01f, 0.52f, 0.59f)),
    ACACIA_FENCE(BlockShape.FENCE, Color.getHSBColor(0.01f, 0.52f, 0.59f)),
    ACACIA_FENCE_GATE(BlockShape.FENCE, Color.getHSBColor(0.01f, 0.52f, 0.59f)),
    ACACIA_LEAVES(BlockShape.CUBE, Color.GREEN),
    ACACIA_LOG(BlockShape.CUBE, Color.getHSBColor(0.01f, 0.52f, 0.59f)),
    ACACIA_PLANKS(BlockShape.CUBE, Color.getHSBColor(0.01f, 0.52f, 0.59f)),
    ACACIA_PRESSURE_PLATE(BlockShape.FLAT, Color.getHSBColor(0.01f, 0.52f, 0.59f)),
    ACACIA_SAPLING(BlockShape.PLANT, Color.GREEN),
    ACACIA_SIGN(BlockShape.FENCE, Color.getHSBColor(0.01f, 0.52f, 0.59f)),
    ACACIA_SLAB(BlockShape.SLAB, Color.getHSBColor(0.01f, 0.52f, 0.59f)),
    ACACIA_STAIRS(BlockShape.STAIR, Color.getHSBColor(0.01f, 0.52f, 0.59f)),
    ACACIA_TRAPDOOR(BlockShape.FLAT, Color.getHSBColor(0.01f, 0.52f, 0.59f)),
    ACACIA_WALL_SIGN(BlockShape.FENCE, Color.getHSBColor(0.01f, 0.52f, 0.59f)),
    ACACIA_WOOD(BlockShape.CUBE, Color.getHSBColor(0.01f, 0.52f, 0.59f)),
    ACTIVATOR_RAIL(BlockShape.FLAT, Color.RED),
    AIR(BlockShape.VOID, Color.GREEN),
    ALLIUM(BlockShape.PLANT, Color.MAGENTA),
    AMETHYST_BLOCK(BlockShape.CUBE, Color.MAGENTA),
    AMETHYST_CLUSTER(BlockShape.PLANT, Color.MAGENTA),
    ANCIENT_DEBRIS(BlockShape.CUBE, Color.GRAY),
    ANDESITE(BlockShape.CUBE),
    ANDESITE_SLAB(BlockShape.SLAB),
    ANDESITE_STAIRS(BlockShape.STAIR),
    ANDESITE_WALL(BlockShape.FENCE),
    ANVIL(BlockShape.CUBE, Color.BLACK),
    ATTACHED_MELON_STEM(BlockShape.PLANT),
    ATTACHED_PUMPKIN_STEM(BlockShape.PLANT),
    AZALEA(BlockShape.CUBE),
    AZALEA_LEAVES(BlockShape.CUBE),
    AZURE_BLUET(BlockShape.PLANT),
    BAMBOO(BlockShape.PLANT),
    BAMB00_SHOOT(BlockShape.PLANT),
    BARREL(BlockShape.CUBE),
    BARRIER(BlockShape.VOID, Color.WHITE),
    BASALT(BlockShape.CUBE),
    BEACON(BlockShape.CUBE, Color.CYAN),
    BEDROCK(BlockShape.CUBE, Color.BLACK),
    BEE_NEST(BlockShape.CUBE),
    BEEHIVE(BlockShape.CUBE),
    BEETROOTS(BlockShape.PLANT),
    BELL(BlockShape.SMALL),
    BIG_DRIPLEAF(BlockShape.FLAT),
    BIG_DRIPLEAF_STEM(BlockShape.PLANT),
    BIRCH_BUTTON(BlockShape.SMALL),
    BIRCH_DOOR(BlockShape.DOOR, Color.getHSBColor(0.07f, 0.71f, 0.64f)),
    BIRCH_FENCE(BlockShape.FENCE, Color.getHSBColor(0.07f, 0.71f, 0.64f)),
    BIRCH_FENCE_GATE(BlockShape.FENCE, Color.getHSBColor(0.07f, 0.71f, 0.64f)),
    BIRCH_LEAVES(BlockShape.CUBE),
    BIRCH_LOG(BlockShape.CUBE),
    BIRCH_PLANKS(BlockShape.CUBE),
    BIRCH_PRESSURE_PLATE(BlockShape.FLAT),
    BIRCH_SAPLING(BlockShape.PLANT),
    BIRCH_SIGN(BlockShape.FENCE),
    BIRCH_SLAB(BlockShape.SLAB),
    BIRCH_STAIRS(BlockShape.STAIR, Color.getHSBColor(0.07f, 0.71f, 0.64f)),
    BIRCH_TRAPDOOR(BlockShape.FLAT),
    BIRCH_WALL_SIGN(BlockShape.FENCE),
    BIRCH_WOOD(BlockShape.CUBE),
    BLACK_BANNER(BlockShape.DOOR),
    BLACK_BED(BlockShape.SLAB),
    BLACK_CANDLE(BlockShape.PLANT),
    BLACK_CANDLE_CAKE(BlockShape.SLAB),
    BLACK_CARPET(BlockShape.FLAT),
    BLACK_CONCRETE(BlockShape.CUBE),
    BLACK_CONCRETE_POWDER(BlockShape.CUBE),
    BLACK_GLAZED_TERRACOTTA(BlockShape.CUBE),
    BLACK_SHULKER_BOX(BlockShape.CUBE),
    BLACK_STAINED_GLASS(BlockShape.CUBE),
    BLACK_STAINED_GLASS_PANE(BlockShape.FENCE),
    BLACK_TERRACOTTA(BlockShape.CUBE),
    BLACK_WALL_BANNER(BlockShape.DOOR),
    BLACK_WOOL(BlockShape.CUBE),
    BLACKSTONE(BlockShape.CUBE),
    BLACKSTONE_SLAB(BlockShape.SLAB),
    BLACKSTONE_STAIRS(BlockShape.STAIR),
    BLACKSTONE_WALL(BlockShape.FENCE),
    BLAST_FURNACE(BlockShape.CUBE),
    BLUE_BANNER(BlockShape.DOOR),
    BLUE_BED(BlockShape.SLAB),
    BLUE_CANDLE(BlockShape.PLANT),
    BLUE_CANDLE_CAKE(BlockShape.SLAB),
    BLUE_CARPET(BlockShape.FLAT),
    BLUE_CONCRETE(BlockShape.CUBE),
    BLUE_CONCRETE_POWDER(BlockShape.CUBE),
    BLUE_GLAZED_TERRACOTTA(BlockShape.CUBE),
    BLUE_ICE(BlockShape.CUBE),
    BLUE_ORCHID(BlockShape.PLANT),
    BLUE_SHULKER_BOX(BlockShape.CUBE),
    BLUE_STAINED_GLASS(BlockShape.CUBE),
    BLUE_STAINED_GLASS_PANE(BlockShape.FENCE),
    BLUE_TERRACOTTA(BlockShape.CUBE),
    BLUE_WALL_BANNER(BlockShape.DOOR),
    BLUE_WOOL(BlockShape.CUBE),
    BONE_BLOCK(BlockShape.CUBE),
    BOOKSHELF(BlockShape.CUBE, Color.getHSBColor(0.11f, 1.0f, 0.4f)),
    BRAIN_CORAL(BlockShape.PLANT),
    BRAIN_CORAL_BLOCK(BlockShape.CUBE),
    BRAIN_CORAL_FAN(BlockShape.PLANT),
    BRAIN_CORAL_WALL_FAN(BlockShape.PLANT),
    BREWING_STAND(BlockShape.PLANT, Color.getHSBColor(0.1f, 0.78f, 0.98f)),
    BRICK_SLAB(BlockShape.SLAB),
    BRICK_STAIRS(BlockShape.STAIR, Color.getHSBColor(0.01f, 0.83f, 0.62f)),
    BRICK_WALL(BlockShape.FENCE),
    BRICKS(BlockShape.CUBE, Color.getHSBColor(0.01f, 0.83f, 0.62f)),
    BROWN_BANNER(BlockShape.DOOR),
    BROWN_BED(BlockShape.SLAB),
    BROWN_CANDLE(BlockShape.PLANT),
    BROWN_CANDLE_CAKE(BlockShape.SLAB),
    BROWN_CARPET(BlockShape.FLAT),
    BROWN_CONCRETE(BlockShape.CUBE),
    BROWN_CONCRETE_POWDER(BlockShape.CUBE),
    BROWN_GLAZED_TERRACOTTA(BlockShape.CUBE),
    BROWN_MUSHROOM(BlockShape.PLANT, Color.getHSBColor(0.09f, 0.17f, 0.8f)),
    BROWN_MUSHROOM_BLOCK(BlockShape.CUBE),
    BROWN_SHULKER_BOX(BlockShape.CUBE),
    BROWN_STAINED_GLASS(BlockShape.CUBE),
    BROWN_STAINED_GLASS_PANE(BlockShape.FENCE),
    BROWN_TERRACOTTA(BlockShape.CUBE),
    BROWN_WALL_BANNER(BlockShape.DOOR),
    BROWN_WOOL(BlockShape.CUBE),
    BUBBLE_COLUMN(BlockShape.VOID),
    BUBBLE_CORAL(BlockShape.PLANT),
    BUBBLE_CORAL_BLOCK(BlockShape.CUBE),
    BUBBLE_CORAL_FAN(BlockShape.PLANT),
    BUBBLE_CORAL_WALL_FAN(BlockShape.PLANT),
    BUDDING_AMETHYST(BlockShape.CUBE),
    CACTUS(BlockShape.CUBE, Color.getHSBColor(0.41f, 0.93f, 0.29f)),
    CAKE(BlockShape.SLAB, Color.getHSBColor(0.06f, 0.59f, 0.79f)),
    CALCITE(BlockShape.CUBE),
    CAMPFIRE(BlockShape.SLAB),
    CANDLE(BlockShape.PLANT),
    CANDLE_CAKE(BlockShape.SLAB),
    CARROTS(BlockShape.PLANT, Color.getHSBColor(0.1f, 0.83f, 0.99f)),
    CARTOGRAPHY_TABLE(BlockShape.CUBE),
    CARVED_PUMPKIN(BlockShape.CUBE),
    CAULDRON(BlockShape.CUBE, Color.DARK_GRAY),
    CAVE_AIR(BlockShape.VOID),
    CAVE_VINES(BlockShape.PLANT),
    CAVE_VINES_PLANT(BlockShape.PLANT),
    CHAIN(BlockShape.PLANT),
    CHAIN_COMMAND_BLOCK(BlockShape.CUBE),
    CHEST(BlockShape.CUBE, Color.getHSBColor(0.11f, 1.0f, 0.4f)),
    CHIPPED_ANVIL(BlockShape.CUBE),
    CHISELED_DEEPSLATE(BlockShape.CUBE),
    CHISELED_NETHER_BRICKS(BlockShape.CUBE),
    CHISELED_POLISHED_BLACKSTONE(BlockShape.CUBE),
    CHISELED_QUARTZ_BLOCK(BlockShape.CUBE),
    CHISELED_RED_SANDSTONE(BlockShape.CUBE),
    CHISELED_SANDSTONE(BlockShape.CUBE),
    CHISELED_STONE_BRICKS(BlockShape.CUBE),
    CHORUS_FLOWER(BlockShape.CUBE),
    CHORUS_PLANT(BlockShape.FENCE),
    CLAY(BlockShape.CUBE, Color.getHSBColor(0.09f, 0.24f, 0.73f)),
    COAL_BLOCK(BlockShape.CUBE, Color.BLACK),
    COAL_ORE(BlockShape.CUBE, Color.BLACK),
    COARSE_DIRT(BlockShape.CUBE),
    COBBLED_DEEPSLATE(BlockShape.CUBE),
    COBBLED_DEEPSLATE_SLAB(BlockShape.SLAB),
    COBBLED_DEEPSLATE_STAIRS(BlockShape.STAIR),
    COBBLED_DEEPSLATE_WALL(BlockShape.FENCE),
    COBBLESTONE(BlockShape.CUBE, Color.LIGHT_GRAY),
    COBBLESTONE_SLAB(BlockShape.SLAB),
    COBBLESTONE_STAIRS(BlockShape.STAIR, Color.LIGHT_GRAY),
    COBBLESTONE_WALL(BlockShape.FENCE, Color.LIGHT_GRAY),
    COBWEB(BlockShape.CUBE),
    COCOA(BlockShape.SMALL, Color.getHSBColor(0.11f, 1.0f, 0.4f)),
    COMMAND_BLOCK(BlockShape.CUBE, Color.DARK_GRAY),
    COMPARATOR(BlockShape.FLAT),
    COMPOSTER(BlockShape.CUBE),
    CONDUIT(BlockShape.SMALL),
    COPPER_BLOCK(BlockShape.CUBE),
    COPPER_ORE(BlockShape.CUBE),
    CORNFLOWER(BlockShape.PLANT),
    CRACKED_DEEPSLATE_BRICKS(BlockShape.CUBE),
    CRACKED_DEEPSLATE_TILES(BlockShape.CUBE),
    CRACKED_NETHER_BRICKS(BlockShape.CUBE),
    CRACKED_POLISHED_BLACKSTONE_BRICKS(BlockShape.CUBE),
    CRACKED_STONE_BRICKS(BlockShape.CUBE),
    CRAFTING_TABLE(BlockShape.CUBE, Color.getHSBColor(0.11f, 1.0f, 0.4f)),
    CREEPER_HEAD(BlockShape.SMALL),
    CREEPER_WALL_HEAD(BlockShape.SMALL),
    CRIMSON_BUTTON(BlockShape.SMALL),
    CRIMSON_DOOR(BlockShape.DOOR),
    CRIMSON_FENCE(BlockShape.FENCE),
    CRIMSON_FENCE_GATE(BlockShape.FENCE),
    CRIMSON_FUNGUS(BlockShape.PLANT),
    CRIMSON_HYPHAE(BlockShape.CUBE),
    CRIMSON_NYLIUM(BlockShape.CUBE),
    CRIMSON_PLANKS(BlockShape.CUBE),
    CRIMSON_PRESSURE_PLATE(BlockShape.FLAT),
    CRIMSON_ROOTS(BlockShape.PLANT),
    CRIMSON_SIGN(BlockShape.FENCE),
    CRIMSON_SLAB(BlockShape.SLAB),
    CRIMSON_STAIRS(BlockShape.STAIR),
    CRIMSON_STEM(BlockShape.CUBE),
    CRIMSON_TRAPDOOR(BlockShape.FLAT),
    CRIMSON_WALL_SIGN(BlockShape.FENCE),
    CRYING_OBSIDIAN(BlockShape.CUBE),
    CUT_COPPER(BlockShape.CUBE),
    CUT_COPPER_SLAB(BlockShape.SLAB),
    CUT_COPPER_STAIRS(BlockShape.STAIR),
    CUT_RED_SANDSTONE(BlockShape.CUBE),
    CUT_RED_SANDSTONE_SLAB(BlockShape.SLAB),
    CUT_SANDSTONE(BlockShape.CUBE),
    CUT_SANDSTONE_SLAB(BlockShape.SLAB),
    CYAN_BANNER(BlockShape.DOOR),
    CYAN_BED(BlockShape.SLAB),
    CYAN_CANDLE(BlockShape.PLANT),
    CYAN_CANDLE_CAKE(BlockShape.SLAB),
    CYAN_CARPET(BlockShape.FLAT),
    CYAN_CONCRETE(BlockShape.CUBE),
    CYAN_CONCRETE_POWDER(BlockShape.CUBE),
    CYAN_GLAZED_TERRACOTTA(BlockShape.CUBE),
    CYAN_SHULKER_BOX(BlockShape.CUBE),
    CYAN_STAINED_GLASS(BlockShape.CUBE),
    CYAN_STAINED_GLASS_PANE(BlockShape.FENCE),
    CYAN_TERRACOTTA(BlockShape.CUBE),
    CYAN_WALL_BANNER(BlockShape.DOOR),
    CYAN_WOOL(BlockShape.CUBE),
    DAMAGED_ANVIL(BlockShape.CUBE),
    DANDELION(BlockShape.PLANT),
    DARK_OAK_BUTTON(BlockShape.SMALL),
    DARK_OAK_DOOR(BlockShape.DOOR, Color.getHSBColor(0.04f, 0.75f, 0.37f)),
    DARK_OAK_FENCE(BlockShape.FENCE, Color.getHSBColor(0.04f, 0.75f, 0.37f)),
    DARK_OAK_FENCE_GATE(BlockShape.FENCE, Color.getHSBColor(0.04f, 0.75f, 0.37f)),
    DARK_OAK_LEAVES(BlockShape.CUBE),
    DARK_OAK_LOG(BlockShape.CUBE),
    DARK_OAK_PLANKS(BlockShape.CUBE),
    DARK_OAK_PRESSURE_PLATE(BlockShape.FLAT),
    DARK_OAK_SAPLING(BlockShape.PLANT),
    DARK_OAK_SIGN(BlockShape.FENCE),
    DARK_OAK_SLAB(BlockShape.SLAB),
    DARK_OAK_STAIRS(BlockShape.STAIR, Color.getHSBColor(0.04f, 0.75f, 0.37f)),
    DARK_OAK_TRAPDOOR(BlockShape.FLAT),
    DARK_OAK_WALL_SIGN(BlockShape.FENCE),
    DARK_OAK_WOOD(BlockShape.CUBE),
    DARK_PRISMARINE(BlockShape.CUBE),
    DARK_PRISMARINE_SLAB(BlockShape.SLAB),
    DARK_PRISMARINE_STAIRS(BlockShape.STAIR),
    DAYLIGHT_DETECTOR(BlockShape.SLAB, Color.getHSBColor(0.0f, 0.0f, 0.78f)),
    DEAD_BRAIN_CORAL(BlockShape.PLANT),
    DEAD_BRAIN_CORAL_BLOCK(BlockShape.CUBE),
    DEAD_BRAIN_CORAL_FAN(BlockShape.PLANT),
    DEAD_BRAIN_CORAL_WALL_FAN(BlockShape.PLANT),
    DEAD_BUBBLE_CORAL(BlockShape.PLANT),
    DEAD_BUBBLE_CORAL_BLOCK(BlockShape.CUBE),
    DEAD_BUBBLE_CORAL_FAN(BlockShape.PLANT),
    DEAD_BUBBLE_CORAL_WALL_FAN(BlockShape.PLANT),
    DEAD_BUSH(BlockShape.PLANT, Color.getHSBColor(0.13f, 0.15f, 0.98f)),
    DEAD_FIRE_CORAL(BlockShape.PLANT),
    DEAD_FIRE_CORAL_BLOCK(BlockShape.CUBE),
    DEAD_FIRE_CORAL_FAN(BlockShape.PLANT),
    DEAD_FIRE_CORAL_WALL_FAN(BlockShape.PLANT),
    DEAD_HORN_CORAL(BlockShape.PLANT),
    DEAD_HORN_CORAL_BLOCK(BlockShape.CUBE),
    DEAD_HORN_CORAL_FAN(BlockShape.PLANT),
    DEAD_HORN_CORAL_WALL_FAN(BlockShape.PLANT),
    DEAD_TUBE_CORAL(BlockShape.PLANT),
    DEAD_TUBE_CORAL_BLOCK(BlockShape.CUBE),
    DEAD_TUBE_CORAL_FAN(BlockShape.PLANT),
    DEAD_TUBE_CORAL_WALL_FAN(BlockShape.PLANT),
    DEEPSLATE(BlockShape.CUBE),
    DEEPSLATE_BRICK_SLAB(BlockShape.SLAB),
    DEEPSLATE_BRICK_STAIRS(BlockShape.STAIR),
    DEEPSLATE_BRICK_WALL(BlockShape.FENCE),
    DEEPSLATE_BRICKS(BlockShape.CUBE),
    DEEPSLATE_COAL_ORE(BlockShape.CUBE),
    DEEPSLATE_COPPER_ORE(BlockShape.CUBE),
    DEEPSLATE_DIAMOND_ORE(BlockShape.CUBE),
    DEEPSLATE_EMERALD_ORE(BlockShape.CUBE),
    DEEPSLATE_GOLD_ORE(BlockShape.CUBE),
    DEEPSLATE_IRON_ORE(BlockShape.CUBE),
    DEEPSLATE_LAPIS_ORE(BlockShape.CUBE),
    DEEPSLATE_REDSTONE_ORE(BlockShape.CUBE),
    DETECTOR_RAIL(BlockShape.FLAT, Color.GRAY),
    DIAMOND_BLOCK(BlockShape.CUBE, Color.getHSBColor(0.48f, 0.45f, 0.98f)),
    DIAMOND_ORE(BlockShape.CUBE, Color.getHSBColor(0.48f, 0.45f, 0.98f)),
    DIORITE(BlockShape.CUBE),
    DIORITE_SLAB(BlockShape.SLAB),
    DIORITE_STAIRS(BlockShape.STAIR),
    DIORITE_WALL(BlockShape.FENCE),
    DIRT(BlockShape.CUBE, Color.getHSBColor(0.09f, 0.52f, 0.58f)),
    DIRT_PATH(BlockShape.CUBE),
    DISPENSER(BlockShape.CUBE, Color.LIGHT_GRAY),
    DRAGON_EGG(BlockShape.CUBE, Color.getHSBColor(0.84f, 0.85f, 0.49f)),
    DRAGON_HEAD(BlockShape.SMALL),
    DRAGON_WALL_HEAD(BlockShape.SMALL),
    DRIED_KELP(BlockShape.PLANT),
    DRIPSTONE_BLOCK(BlockShape.CUBE),
    DROPPER(BlockShape.CUBE, Color.GRAY),
    EMERALD_BLOCK(BlockShape.CUBE, Color.GREEN),
    EMERALD_ORE(BlockShape.CUBE, Color.GREEN),
    ENCHANTING_TABLE(BlockShape.CUBE, Color.CYAN),
    END_GATEWAY(BlockShape.CUBE),
    END_PORTAL(BlockShape.FLAT, Color.BLACK),
    END_PORTAL_FRAME(BlockShape.CUBE, Color.WHITE),
    END_ROD(BlockShape.PLANT),
    END_STONE(BlockShape.CUBE, Color.getHSBColor(0.09f, 0.14f, 0.87f)),
    END_STONE_BRICK_SLAB(BlockShape.SLAB),
    END_STONE_BRICK_STAIRS(BlockShape.STAIR),
    END_STONE_BRICK_WALL(BlockShape.FENCE),
    END_STONE_BRICKS(BlockShape.CUBE),
    ENDER_CHEST(BlockShape.CUBE, Color.GREEN),
    EXPOSED_COPPER(BlockShape.CUBE),
    EXPOSED_CUT_COPPER(BlockShape.CUBE),
    EXPOSED_CUT_COPPER_SLAB(BlockShape.SLAB),
    EXPOSED_CUT_COPPER_STAIRS(BlockShape.STAIR),
    FARMLAND(BlockShape.CUBE),
    FERN(BlockShape.PLANT),
    FIRE(BlockShape.CUBE, Color.ORANGE),
    FIRE_CORAL(BlockShape.PLANT),
    FIRE_CORAL_BLOCK(BlockShape.CUBE),
    FIRE_CORAL_FAN(BlockShape.PLANT),
    FIRE_CORAL_WALL_FAN(BlockShape.PLANT),
    FLETCHING_TABLE(BlockShape.CUBE),
    FLOWER_POT(BlockShape.SMALL, Color.RED),
    FLOWERING_AZALEA(BlockShape.CUBE),
    FLOWERING_AZALEA_LEAVES(BlockShape.CUBE),
    FLOWING_LAVA(BlockShape.CUBE, Color.ORANGE),
    FLOWING_WATER(BlockShape.CUBE, Color.BLUE),
    FROSTED_ICE(BlockShape.CUBE),
    FURNACE(BlockShape.CUBE, Color.LIGHT_GRAY),
    GILDED_BLACKSTONE(BlockShape.CUBE),
    GLASS(BlockShape.CUBE, Color.WHITE),
    GLASS_PANE(BlockShape.FENCE),
    GLOW_LICHEN(BlockShape.DOOR),
    GLOWSTONE(BlockShape.CUBE, Color.YELLOW),
    GOLD_BLOCK(BlockShape.CUBE, Color.ORANGE),
    GOLD_ORE(BlockShape.CUBE, Color.ORANGE),
    GRANITE(BlockShape.CUBE),
    GRANITE_SLAB(BlockShape.SLAB),
    GRANITE_STAIRS(BlockShape.STAIR),
    GRANITE_WALL(BlockShape.FENCE),
    GRASS(BlockShape.PLANT),
    GRASS_BLOCK(BlockShape.CUBE, Color.GREEN),
    GRAVEL(BlockShape.CUBE, Color.DARK_GRAY),
    GRAY_BANNER(BlockShape.DOOR),
    GRAY_BED(BlockShape.SLAB),
    GRAY_CANDLE(BlockShape.PLANT),
    GRAY_CANDLE_CAKE(BlockShape.SLAB),
    GRAY_CARPET(BlockShape.FLAT),
    GRAY_CONCRETE(BlockShape.CUBE),
    GRAY_CONCRETE_POWDER(BlockShape.CUBE),
    GRAY_GLAZED_TERRACOTTA(BlockShape.CUBE),
    GRAY_SHULKER_BOX(BlockShape.CUBE),
    GRAY_STAINED_GLASS(BlockShape.CUBE),
    GRAY_STAINED_GLASS_PANE(BlockShape.FENCE),
    GRAY_TERRACOTTA(BlockShape.CUBE),
    GRAY_WALL_BANNER(BlockShape.DOOR),
    GRAY_WOOL(BlockShape.CUBE),
    GREEN_BANNER(BlockShape.DOOR),
    GREEN_BED(BlockShape.SLAB),
    GREEN_CANDLE(BlockShape.PLANT),
    GREEN_CANDLE_CAKE(BlockShape.SLAB),
    GREEN_CARPET(BlockShape.FLAT),
    GREEN_CONCRETE(BlockShape.CUBE),
    GREEN_CONCRETE_POWDER(BlockShape.CUBE),
    GREEN_GLAZED_TERRACOTTA(BlockShape.CUBE),
    GREEN_SHULKER_BOX(BlockShape.CUBE),
    GREEN_STAINED_GLASS(BlockShape.CUBE),
    GREEN_STAINED_GLASS_PANE(BlockShape.FENCE),
    GREEN_TERRACOTTA(BlockShape.CUBE),
    GREEN_WALL_BANNER(BlockShape.DOOR),
    GREEN_WOOL(BlockShape.CUBE),
    GRINDSTONE(BlockShape.CUBE),
    HANGING_ROOTS(BlockShape.PLANT),
    HAY_BLOCK(BlockShape.CUBE, Color.YELLOW),
    HEAVY_WEIGHTED_PRESSURE_PLATE(BlockShape.FLAT, Color.LIGHT_GRAY),
    HOPPER(BlockShape.CUBE, Color.BLACK),
    HONEY_BLOCK(BlockShape.CUBE),
    HONEYCOMB_BLOCK(BlockShape.CUBE),
    HORN_CORAL(BlockShape.PLANT),
    HORN_CORAL_BLOCK(BlockShape.CUBE),
    HORN_CORAL_FAN(BlockShape.PLANT),
    HORN_CORAL_WALL_FAN(BlockShape.PLANT),
    ICE(BlockShape.CUBE, Color.CYAN),
    INFESTED_CHISELED_STONE_BRICKS(BlockShape.CUBE),
    INFESTED_COBBLESTONE(BlockShape.CUBE),
    INFESTED_CRACKED_STONE_BRICKS(BlockShape.CUBE),
    INFESTED_DEEPSLATE(BlockShape.CUBE),
    INFESTED_MOSSY_STONE_BRICKS(BlockShape.CUBE),
    INFESTED_STONE(BlockShape.CUBE),
    INFESTED_STONE_BRICKS(BlockShape.CUBE),
    IRON_BARS(BlockShape.FENCE, Color.getHSBColor(0f, 0f, 0.6f)),
    IRON_BLOCK(BlockShape.CUBE, Color.LIGHT_GRAY),
    IRON_DOOR(BlockShape.DOOR, Color.LIGHT_GRAY),
    IRON_ORE(BlockShape.CUBE, Color.GRAY),
    IRON_TRAPDOOR(BlockShape.FLAT, Color.LIGHT_GRAY),
    JACK_O_LANTERN(BlockShape.CUBE, Color.ORANGE),
    JIGSAW(BlockShape.CUBE),
    JUKEBOX(BlockShape.CUBE, Color.getHSBColor(0.11f, 1.0f, 0.4f)),
    JUNGLE_BUTTON(BlockShape.SMALL),
    JUNGLE_DOOR(BlockShape.DOOR, Color.getHSBColor(0.1f, 0.7f, 0.64f)),
    JUNGLE_FENCE(BlockShape.FENCE, Color.getHSBColor(0.1f, 0.7f, 0.64f)),
    JUNGLE_FENCE_GATE(BlockShape.FENCE, Color.getHSBColor(0.1f, 0.7f, 0.64f)),
    JUNGLE_LEAVES(BlockShape.CUBE),
    JUNGLE_LOG(BlockShape.CUBE),
    JUNGLE_PLANKS(BlockShape.CUBE),
    JUNGLE_PRESSURE_PLATE(BlockShape.FLAT),
    JUNGLE_SAPLING(BlockShape.PLANT),
    JUNGLE_SIGN(BlockShape.DOOR),
    JUNGLE_SLAB(BlockShape.SLAB),
    JUNGLE_STAIRS(BlockShape.STAIR, Color.getHSBColor(0.1f, 0.7f, 0.64f)),
    JUNGLE_TRAPDOOR(BlockShape.FLAT),
    JUNGLE_WALL_SIGN(BlockShape.DOOR),
    JUNGLE_WOOD(BlockShape.CUBE),
    KELP(BlockShape.PLANT),
    KELP_PLANT(BlockShape.PLANT),
    LADDER(BlockShape.DOOR, Color.getHSBColor(0.11f, 1.0f, 0.4f)),
    LANTERN(BlockShape.SMALL),
    LAPIS_BLOCK(BlockShape.CUBE, Color.BLUE),
    LAPIS_ORE(BlockShape.CUBE, Color.BLUE),
    LARGE_AMETHYST_BUD(BlockShape.PLANT),
    LARGE_FERN(BlockShape.PLANT),
    LAVA(BlockShape.CUBE, Color.ORANGE),
    LAVA_CAULDRON(BlockShape.CUBE),
    LECTERN(BlockShape.CUBE),
    LEVER(BlockShape.STICK, Color.getHSBColor(0.11f, 1.0f, 0.4f)),
    LIGHT(BlockShape.VOID),
    LIGHT_BLUE_BANNER(BlockShape.DOOR),
    LIGHT_BLUE_BED(BlockShape.SLAB),
    LIGHT_BLUE_CANDLE(BlockShape.PLANT),
    LIGHT_BLUE_CANDLE_CAKE(BlockShape.SLAB),
    LIGHT_BLUE_CARPET(BlockShape.FLAT),
    LIGHT_BLUE_CONCRETE(BlockShape.CUBE),
    LIGHT_BLUE_CONCRETE_POWDER(BlockShape.CUBE),
    LIGHT_BLUE_GLAZED_TERRACOTTA(BlockShape.CUBE),
    LIGHT_BLUE_SHULKER_BOX(BlockShape.CUBE),
    LIGHT_BLUE_STAINED_GLASS(BlockShape.CUBE),
    LIGHT_BLUE_STAINED_GLASS_PANE(BlockShape.FENCE),
    LIGHT_BLUE_TERRACOTTA(BlockShape.CUBE),
    LIGHT_BLUE_WALL_BANNER(BlockShape.DOOR),
    LIGHT_BLUE_WOOL(BlockShape.CUBE),
    LIGHT_GRAY_BANNER(BlockShape.DOOR),
    LIGHT_GRAY_BED(BlockShape.SLAB),
    LIGHT_GRAY_CANDLE(BlockShape.PLANT),
    LIGHT_GRAY_CANDLE_CAKE(BlockShape.SLAB),
    LIGHT_GRAY_CARPET(BlockShape.FLAT),
    LIGHT_GRAY_CONCRETE(BlockShape.CUBE),
    LIGHT_GRAY_CONCRETE_POWDER(BlockShape.CUBE),
    LIGHT_GRAY_GLAZED_TERRACOTTA(BlockShape.CUBE),
    LIGHT_GRAY_SHULKER_BOX(BlockShape.CUBE),
    LIGHT_GRAY_STAINED_GLASS(BlockShape.CUBE),
    LIGHT_GRAY_STAINED_GLASS_PANE(BlockShape.FENCE),
    LIGHT_GRAY_TERRACOTTA(BlockShape.CUBE),
    LIGHT_GRAY_WALL_BANNER(BlockShape.DOOR),
    LIGHT_GRAY_WOOL(BlockShape.CUBE),
    LIGHT_WEIGHTED_PRESSURE_PLATE(BlockShape.FLAT),
    LIGHTNING_ROD(BlockShape.PLANT),
    LILAC(BlockShape.PLANT),
    LILY_OF_THE_VALLEY(BlockShape.PLANT),
    LILY_PAD(BlockShape.FLAT),
    LIME_BANNER(BlockShape.DOOR),
    LIME_BED(BlockShape.SLAB),
    LIME_CANDLE(BlockShape.PLANT),
    LIME_CANDLE_CAKE(BlockShape.SLAB),
    LIME_CARPET(BlockShape.FLAT),
    LIME_CONCRETE(BlockShape.CUBE),
    LIME_CONCRETE_POWDER(BlockShape.CUBE),
    LIME_GLAZED_TERRACOTTA(BlockShape.CUBE),
    LIME_SHULKER_BOX(BlockShape.CUBE),
    LIME_STAINED_GLASS(BlockShape.CUBE),
    LIME_STAINED_GLASS_PANE(BlockShape.FENCE),
    LIME_TERRACOTTA(BlockShape.CUBE),
    LIME_WALL_BANNER(BlockShape.DOOR),
    LIME_WOOL(BlockShape.CUBE),
    LODESTONE(BlockShape.CUBE),
    LOOM(BlockShape.CUBE),
    MAGENTA_BANNER(BlockShape.DOOR),
    MAGENTA_BED(BlockShape.SLAB),
    MAGENTA_CANDLE(BlockShape.PLANT),
    MAGENTA_CANDLE_CAKE(BlockShape.SLAB),
    MAGENTA_CARPET(BlockShape.FLAT),
    MAGENTA_CONCRETE(BlockShape.CUBE),
    MAGENTA_CONCRETE_POWDER(BlockShape.CUBE),
    MAGENTA_GLAZED_TERRACOTTA(BlockShape.CUBE),
    MAGENTA_SHULKER_BOX(BlockShape.CUBE),
    MAGENTA_STAINED_GLASS(BlockShape.CUBE),
    MAGENTA_STAINED_GLASS_PANE(BlockShape.FENCE),
    MAGENTA_TERRACOTTA(BlockShape.CUBE),
    MAGENTA_WALL_BANNER(BlockShape.DOOR),
    MAGENTA_WOOL(BlockShape.CUBE),
    MAGMA_BLOCK(BlockShape.CUBE),
    MEDIUM_AMETHYST_BUD(BlockShape.PLANT),
    MELON(BlockShape.CUBE, Color.GREEN),
    MELON_STEM(BlockShape.PLANT, Color.GREEN),
    MOSS_BLOCK(BlockShape.CUBE),
    MOSS_CARPET(BlockShape.FLAT),
    MOSSY_COBBLESTONE(BlockShape.CUBE, Color.LIGHT_GRAY),
    MOSSY_COBBLESTONE_SLAB(BlockShape.SLAB),
    MOSSY_COBBLESTONE_STAIRS(BlockShape.STAIR),
    MOSSY_COBBLESTONE_WALL(BlockShape.FENCE),
    MOSSY_STONE_BRICK_SLAB(BlockShape.SLAB),
    MOSSY_STONE_BRICK_STAIRS(BlockShape.STAIR),
    MOSSY_STONE_BRICK_WALL(BlockShape.FENCE),
    MOSSY_STONE_BRICKS(BlockShape.CUBE),
    MOVING_PISTON(BlockShape.VOID),
    MUSHROOM_STEM(BlockShape.CUBE),
    MYCELIUM(BlockShape.CUBE, Color.PINK),
    NETHER_BRICK_FENCE(BlockShape.FENCE, Color.getHSBColor(0.99f, 1f, 0.46f)),
    NETHER_BRICK_SLAB(BlockShape.SLAB),
    NETHER_BRICK_STAIRS(BlockShape.STAIR, Color.getHSBColor(0.99f, 1f, 0.46f)),
    NETHER_BRICK_WALL(BlockShape.FENCE),
    NETHER_BRICKS(BlockShape.CUBE, Color.getHSBColor(0.99f, 1f, 0.46f)),
    NETHER_GOLD_ORE(BlockShape.CUBE),
    NETHER_PORTAL(BlockShape.DOOR, Color.MAGENTA),
    NETHER_QUARTZ_ORE(BlockShape.CUBE),
    NETHER_SPROUTS(BlockShape.PLANT),
    NETHER_WART(BlockShape.PLANT, Color.getHSBColor(0.93f, 0.96f, 0.62f)),
    NETHER_WART_BLOCK(BlockShape.CUBE),
    NETHERITE_BLOCK(BlockShape.CUBE),
    NETHERRACK(BlockShape.CUBE, Color.getHSBColor(0.99f, 1f, 0.46f)),
    NOTE_BLOCK(BlockShape.CUBE, Color.getHSBColor(0.11f, 1.0f, 0.4f)),
    OAK_BUTTON(BlockShape.SMALL, Color.getHSBColor(0.04f, 0.72f, 0.64f)),
    OAK_DOOR(BlockShape.DOOR, Color.getHSBColor(0.04f, 0.72f, 0.64f)),
    OAK_FENCE(BlockShape.FENCE, Color.getHSBColor(0.04f, 0.72f, 0.64f)),
    OAK_FENCE_GATE(BlockShape.FENCE, Color.getHSBColor(0.04f, 0.72f, 0.64f)),
    OAK_LEAVES(BlockShape.CUBE, Color.GREEN),
    OAK_LOG(BlockShape.CUBE, Color.getHSBColor(0.04f, 0.72f, 0.64f)),
    OAK_PLANKS(BlockShape.CUBE, Color.getHSBColor(0.04f, 0.72f, 0.64f)),
    OAK_PRESSURE_PLATE(BlockShape.FLAT, Color.getHSBColor(0.04f, 0.72f, 0.64f)),
    OAK_SAPLING(BlockShape.PLANT, Color.GREEN),
    OAK_SIGN(BlockShape.DOOR, Color.getHSBColor(0.04f, 0.72f, 0.64f)),
    OAK_SLAB(BlockShape.SLAB, Color.getHSBColor(0.04f, 0.72f, 0.64f)),
    OAK_STAIRS(BlockShape.STAIR, Color.getHSBColor(0.04f, 0.72f, 0.64f)),
    OAK_TRAPDOOR(BlockShape.FLAT, Color.getHSBColor(0.04f, 0.72f, 0.64f)),
    OAK_WALL_SIGN(BlockShape.DOOR, Color.getHSBColor(0.04f, 0.72f, 0.64f)),
    OAK_WOOD(BlockShape.CUBE, Color.getHSBColor(0.04f, 0.72f, 0.64f)),
    OBSERVER(BlockShape.CUBE),
    OBSIDIAN(BlockShape.CUBE, Color.getHSBColor(0.87f, 1f, 0.09f)),
    ORANGE_BANNER(BlockShape.DOOR),
    ORANGE_BED(BlockShape.SLAB),
    ORANGE_CANDLE(BlockShape.PLANT),
    ORANGE_CANDLE_CAKE(BlockShape.SLAB),
    ORANGE_CARPET(BlockShape.FLAT),
    ORANGE_CONCRETE(BlockShape.CUBE),
    ORANGE_CONCRETE_POWDER(BlockShape.CUBE),
    ORANGE_GLAZED_TERRACOTTA(BlockShape.CUBE),
    ORANGE_SHULKER_BOX(BlockShape.CUBE),
    ORANGE_STAINED_GLASS(BlockShape.CUBE),
    ORANGE_STAINED_GLASS_PANE(BlockShape.FENCE),
    ORANGE_TERRACOTTA(BlockShape.CUBE),
    ORANGE_TULIP(BlockShape.PLANT),
    ORANGE_WALL_BANNER(BlockShape.DOOR),
    ORANGE_WOOL(BlockShape.CUBE),
    OXEYE_DAISY(BlockShape.PLANT),
    OXIDIZED_COPPER(BlockShape.CUBE),
    OXIDIZED_CUT_COPPER(BlockShape.CUBE),
    OXIDIZED_CUT_COPPER_SLAB(BlockShape.SLAB),
    OXIDIZED_CUT_COPPER_STAIRS(BlockShape.STAIR),
    PACKED_ICE(BlockShape.CUBE, Color.getHSBColor(0.57f, 0.35f, 0.97f)),
    PEONY(BlockShape.PLANT),
    PETRIFIED_OAK_SLAB(BlockShape.SLAB),
    PINK_BANNER(BlockShape.DOOR),
    PINK_BED(BlockShape.SLAB),
    PINK_CANDLE(BlockShape.PLANT),
    PINK_CANDLE_CAKE(BlockShape.SLAB),
    PINK_CARPET(BlockShape.FLAT),
    PINK_CONCRETE(BlockShape.CUBE),
    PINK_CONCRETE_POWDER(BlockShape.CUBE),
    PINK_GLAZED_TERRACOTTA(BlockShape.CUBE),
    PINK_SHULKER_BOX(BlockShape.CUBE),
    PINK_STAINED_GLASS(BlockShape.CUBE),
    PINK_STAINED_GLASS_PANE(BlockShape.FENCE),
    PINK_TERRACOTTA(BlockShape.CUBE),
    PINK_TULIP(BlockShape.PLANT),
    PINK_WALL_BANNER(BlockShape.DOOR),
    PINK_WOOL(BlockShape.CUBE),
    PISTON(BlockShape.CUBE, Color.GRAY),
    PISTON_HEAD(BlockShape.CUBE, Color.GRAY),
    PLAYER_HEAD(BlockShape.SMALL),
    PLAYER_WALL_HEAD(BlockShape.SMALL),
    PODZOL(BlockShape.CUBE),
    POINTED_DRIPSTONE(BlockShape.PLANT),
    POLISHED_ANDESITE(BlockShape.CUBE),
    POLISHED_ANDESITE_SLAB(BlockShape.SLAB),
    POLISHED_ANDESITE_STAIRS(BlockShape.STAIR),
    POLISHED_BASALT(BlockShape.CUBE),
    POLISHED_BLACKSTONE(BlockShape.CUBE),
    POLISHED_BLACKSTONE_BRICK_SLAB(BlockShape.SLAB),
    POLISHED_BLACKSTONE_BRICK_STAIRS(BlockShape.STAIR),
    POLISHED_BLACKSTONE_BRICK_WALL(BlockShape.FENCE),
    POLISHED_BLACKSTONE_BRICKS(BlockShape.CUBE),
    POLISHED_BLACKSTONE_BUTTON(BlockShape.SMALL),
    POLISHED_BLACKSTONE_PRESSURE_PLATE(BlockShape.FLAT),
    POLISHED_BLACKSTONE_SLAB(BlockShape.SLAB),
    POLISHED_BLACKSTONE_STAIRS(BlockShape.STAIR),
    POLISHED_BLACKSTONE_WALL(BlockShape.FENCE),
    POLISHED_DEEPSLATE(BlockShape.CUBE),
    POLISHED_DEEPSLATE_SLAB(BlockShape.SLAB),
    POLISHED_DEEPSLATE_STAIRS(BlockShape.STAIR),
    POLISHED_DEEPSLATE_WALL(BlockShape.FENCE),
    POLISHED_DIORITE(BlockShape.CUBE),
    POLISHED_DIORITE_SLAB(BlockShape.SLAB),
    POLISHED_DIORITE_STAIRS(BlockShape.STAIR),
    POLISHED_GRANITE(BlockShape.CUBE),
    POLISHED_GRANITE_SLAB(BlockShape.SLAB),
    POLISHED_GRANITE_STAIRS(BlockShape.STAIR),
    POPPY(BlockShape.PLANT, Color.RED),
    POTATOES(BlockShape.PLANT, Color.GREEN),
    POTTED_ACACIA_SAPLING(BlockShape.SMALL),
    POTTED_ALLIUM(BlockShape.SMALL),
    POTTED_AZALEA(BlockShape.SMALL),
    POTTED_AZURE_BLUET(BlockShape.SMALL),
    POTTED_BAMBOO(BlockShape.SMALL),
    POTTED_BIRCH_SAPLING(BlockShape.SMALL),
    POTTED_BLUE_ORCHID(BlockShape.SMALL),
    POTTED_BROWN_MUSHROOM(BlockShape.SMALL),
    POTTED_CACTUS(BlockShape.SMALL),
    POTTED_CORNFLOWER(BlockShape.SMALL),
    POTTED_CRIMSON_FUNGUS(BlockShape.SMALL),
    POTTED_CRIMSON_ROOTS(BlockShape.SMALL),
    POTTED_DANDELION(BlockShape.SMALL),
    POTTED_DARK_OAK_SAPLING(BlockShape.SMALL),
    POTTED_DEAD_BUSH(BlockShape.SMALL),
    POTTED_FERN(BlockShape.SMALL),
    POTTED_FLOWERING_AZALEA(BlockShape.SMALL),
    POTTED_JUNGLE_SAPLING(BlockShape.SMALL),
    POTTED_LILY_OF_THE_VALLEY(BlockShape.SMALL),
    POTTED_OAK_SAPLING(BlockShape.SMALL),
    POTTED_ORANGE_TULIP(BlockShape.SMALL),
    POTTED_OXEYE_DAISY(BlockShape.SMALL),
    POTTED_PINK_TULIP(BlockShape.SMALL),
    POTTED_POPPY(BlockShape.SMALL),
    POTTED_RED_MUSHROOM(BlockShape.SMALL),
    POTTED_RED_TULIP(BlockShape.SMALL),
    POTTED_SPRUCE_SAPLING(BlockShape.SMALL),
    POTTED_WARPED_FUNGUS(BlockShape.SMALL),
    POTTED_WARPED_ROOTS(BlockShape.SMALL),
    POTTED_WHITE_TULIP(BlockShape.SMALL),
    POTTED_WITHER_ROSE(BlockShape.SMALL),
    POWDER_SNOW(BlockShape.CUBE),
    POWDER_SNOW_CAULDRON(BlockShape.CUBE),
    POWERED_RAIL(BlockShape.FLAT, Color.RED),
    PRISMARINE(BlockShape.CUBE, Color.getHSBColor(0.55f, 0.56f, 0.74f)),
    PRISMARINE_BRICK_SLAB(BlockShape.SLAB),
    PRISMARINE_BRICK_STAIRS(BlockShape.STAIR),
    PRISMARINE_BRICKS(BlockShape.CUBE),
    PRISMARINE_SLAB(BlockShape.SLAB),
    PRISMARINE_STAIRS(BlockShape.STAIR),
    PRISMARINE_WALL(BlockShape.FENCE),
    PUMPKIN(BlockShape.CUBE, Color.ORANGE),
    PUMPKIN_STEM(BlockShape.PLANT, Color.GREEN),
    PURPLE_BANNER(BlockShape.DOOR),
    PURPLE_BED(BlockShape.SLAB),
    PURPLE_CANDLE(BlockShape.PLANT),
    PURPLE_CANDLE_CAKE(BlockShape.SLAB),
    PURPLE_CARPET(BlockShape.FLAT),
    PURPLE_CONCRETE(BlockShape.CUBE),
    PURPLE_CONCRETE_POWDER(BlockShape.CUBE),
    PURPLE_GLAZED_TERRACOTTA(BlockShape.CUBE),
    PURPLE_SHULKER_BOX(BlockShape.CUBE),
    PURPLE_STAINED_GLASS(BlockShape.CUBE),
    PURPLE_STAINED_GLASS_PANE(BlockShape.FENCE),
    PURPLE_TERRACOTTA(BlockShape.CUBE),
    PURPLE_WALL_BANNER(BlockShape.DOOR),
    PURPLE_WOOL(BlockShape.CUBE),
    PURPUR_BLOCK(BlockShape.CUBE),
    PURPUR_PILLAR(BlockShape.CUBE),
    PURPUR_SLAB(BlockShape.SLAB),
    PURPUR_STAIRS(BlockShape.STAIR),
    QUARTZ_BLOCK(BlockShape.CUBE, Color.getHSBColor(0.04f, 0.05f, 0.98f)),
    QUARTZ_BRICKS(BlockShape.CUBE),
    QUARTZ_PILLAR(BlockShape.CUBE),
    QUARTZ_SLAB(BlockShape.SLAB),
    QUARTZ_STAIRS(BlockShape.STAIR, Color.getHSBColor(0.04f, 0.05f, 0.98f)),
    RAIL(BlockShape.FLAT, Color.GRAY),
    RAW_COPPER_BLOCK(BlockShape.CUBE),
    RAW_GOLD_BLOCK(BlockShape.CUBE),
    RAW_IRON_BLOCK(BlockShape.CUBE),
    RED_BANNER(BlockShape.DOOR),
    RED_BED(BlockShape.SLAB),
    RED_CANDLE(BlockShape.PLANT),
    RED_CANDLE_CAKE(BlockShape.SLAB),
    RED_CARPET(BlockShape.FLAT),
    RED_CONCRETE(BlockShape.CUBE),
    RED_CONCRETE_POWDER(BlockShape.CUBE),
    RED_GLAZED_TERRACOTTA(BlockShape.CUBE),
    RED_MUSHROOM(BlockShape.PLANT, Color.RED),
    RED_MUSHROOM_BLOCK(BlockShape.CUBE),
    RED_NETHER_BRICK_SLAB(BlockShape.SLAB),
    RED_NETHER_BRICK_STAIRS(BlockShape.STAIR),
    RED_NETHER_BRICK_WALL(BlockShape.FENCE),
    RED_NETHER_BRICKS(BlockShape.CUBE),
    RED_SAND(BlockShape.CUBE),
    RED_SANDSTONE(BlockShape.CUBE, Color.getHSBColor(0.06f, 0.64f, 0.66f)),
    RED_SANDSTONE_SLAB(BlockShape.SLAB, Color.getHSBColor(0.06f, 0.64f, 0.66f)),
    RED_SANDSTONE_STAIRS(BlockShape.STAIR, Color.getHSBColor(0.06f, 0.64f, 0.66f)),
    RED_SANDSTONE_WALL(BlockShape.FENCE),
    RED_SHULKER_BOX(BlockShape.CUBE),
    RED_STAINED_GLASS(BlockShape.CUBE),
    RED_STAINED_GLASS_PANE(BlockShape.FENCE),
    RED_TERRACOTTA(BlockShape.CUBE),
    RED_TULIP(BlockShape.PLANT),
    RED_WALL_BANNER(BlockShape.DOOR),
    RED_WOOL(BlockShape.CUBE),
    REDSTONE_BLOCK(BlockShape.CUBE, Color.getHSBColor(0.01f, 0.68f, 0.97f)),
    REDSTONE_LAMP(BlockShape.CUBE, Color.YELLOW),
    REDSTONE_ORE(BlockShape.CUBE, Color.RED),
    REDSTONE_TORCH(BlockShape.STICK, Color.RED),
    REDSTONE_WALL_TORCH(BlockShape.STICK, Color.RED),
    REDSTONE_WIRE(BlockShape.FLAT, Color.RED),
    REPEATER(BlockShape.FLAT),
    REPEATING_COMMAND_BLOCK(BlockShape.CUBE),
    RESPAWN_ANCHOR(BlockShape.CUBE),
    ROOTED_DIRT(BlockShape.CUBE),
    ROSE_BUSH(BlockShape.PLANT),
    SAND(BlockShape.CUBE, Color.getHSBColor(0.15f, 0.27f, 1f)),
    SANDSTONE(BlockShape.CUBE, Color.getHSBColor(0.15f, 0.19f, 0.96f)),
    SANDSTONE_SLAB(BlockShape.SLAB, Color.getHSBColor(0.15f, 0.19f, 0.96f)),
    SANDSTONE_STAIRS(BlockShape.STAIR, Color.getHSBColor(0.15f, 0.19f, 0.96f)),
    SANDSTONE_WALL(BlockShape.FENCE, Color.getHSBColor(0.15f, 0.19f, 0.96f)),
    SCAFFOLDING(BlockShape.CUBE),
    SKULK_SENSOR(BlockShape.SLAB),
    SEA_LANTERN(BlockShape.CUBE, Color.getHSBColor(0.52f, 0.04f, 0.96f)),
    SEA_PICKLE(BlockShape.PLANT),
    SEAGRASS(BlockShape.PLANT),
    SHROOMLIGHT(BlockShape.CUBE),
    SHULKER_BOX(BlockShape.CUBE),
    SKELETON_SKULL(BlockShape.SMALL),
    SKELETON_WALL_SKULL(BlockShape.SMALL),
    SLIME_BLOCK(BlockShape.CUBE, Color.GREEN),
    SMALL_AMETHYST_BUD(BlockShape.PLANT),
    SMALL_DRIPLEAF(BlockShape.PLANT),
    SMITHING_TABLE(BlockShape.CUBE),
    SMOKER(BlockShape.CUBE),
    SMOOTH_BASALT(BlockShape.CUBE),
    SMOOTH_QUARTZ_BLOCK(BlockShape.CUBE),
    SMOOTH_QUARTZ_SLAB(BlockShape.SLAB),
    SMOOTH_QUARTZ_STAIRS(BlockShape.STAIR),
    SMOOTH_RED_SANDSTONE(BlockShape.CUBE),
    SMOOTH_RED_SANDSTONE_SLAB(BlockShape.SLAB),
    SMOOTH_RED_SANDSTONE_STAIRS(BlockShape.STAIR),
    SMOOTH_SANDSTONE(BlockShape.CUBE),
    SMOOTH_SANDSTONE_SLAB(BlockShape.SLAB),
    SMOOTH_SANDSTONE_STAIRS(BlockShape.STAIR),
    SMOOTH_STONE(BlockShape.CUBE, Color.LIGHT_GRAY),
    SMOOTH_STONE_SLAB(BlockShape.SLAB, Color.LIGHT_GRAY),
    SNOW(BlockShape.FLAT, Color.WHITE),
    SNOW_BLOCK(BlockShape.CUBE, Color.WHITE),
    SOUL_CAMPFIRE(BlockShape.SLAB),
    SOUL_FIRE(BlockShape.CUBE),
    SOUL_LANTERN(BlockShape.SMALL),
    SOUL_SAND(BlockShape.CUBE, Color.DARK_GRAY),
    SOUL_SOIL(BlockShape.CUBE),
    SOUL_TORCH(BlockShape.STICK),
    SOUL_WALL_TORCH(BlockShape.STICK),
    SPAWNER(BlockShape.CUBE),
    SPONGE(BlockShape.CUBE, Color.YELLOW),
    SPORE_BLOSSOM(BlockShape.FLAT),
    SPRUCE_BUTTON(BlockShape.SMALL),
    SPRUCE_DOOR(BlockShape.DOOR, Color.getHSBColor(0.07f, 0.58f, 0.5f)),
    SPRUCE_FENCE(BlockShape.FENCE, Color.getHSBColor(0.07f, 0.58f, 0.5f)),
    SPRUCE_FENCE_GATE(BlockShape.FENCE, Color.getHSBColor(0.07f, 0.58f, 0.5f)),
    SPRUCE_LEAVES(BlockShape.CUBE),
    SPRUCE_LOG(BlockShape.CUBE),
    SPRUCE_PLANKS(BlockShape.CUBE),
    SPRUCE_PRESSURE_PLATE(BlockShape.FLAT),
    SPRUCE_SAPLING(BlockShape.PLANT),
    SPRUCE_SIGN(BlockShape.DOOR),
    SPRUCE_SLAB(BlockShape.SLAB),
    SPRUCE_STAIRS(BlockShape.STAIR, Color.getHSBColor(0.07f, 0.58f, 0.5f)),
    SPRUCE_TRAPDOOR(BlockShape.FLAT),
    SPRUCE_WALL_SIGN(BlockShape.DOOR),
    SPRUCE_WOOD(BlockShape.CUBE),
    STICKY_PISTON(BlockShape.CUBE),
    STONE(BlockShape.CUBE, Color.LIGHT_GRAY),
    STONE_BRICK_SLAB(BlockShape.SLAB),
    STONE_BRICK_STAIRS(BlockShape.STAIR, Color.getHSBColor(0f, 0f, 0.46f)),
    STONE_BRICK_WALL(BlockShape.FENCE),
    STONE_BRICKS(BlockShape.CUBE, Color.getHSBColor(0f, 0f, 0.46f)),
    STONE_BUTTON(BlockShape.SMALL, Color.LIGHT_GRAY),
    STONE_PRESSURE_PLATE(BlockShape.FLAT, Color.LIGHT_GRAY),
    STONE_SLAB(BlockShape.SLAB, Color.LIGHT_GRAY),
    STONE_STAIRS(BlockShape.STAIR),
    STONECUTTER(BlockShape.SLAB),
    STRIPPED_ACACIA_LOG(BlockShape.CUBE),
    STRIPPED_ACACIA_WOOD(BlockShape.CUBE),
    STRIPPED_BIRCH_LOG(BlockShape.CUBE),
    STRIPPED_BIRCH_WOOD(BlockShape.CUBE),
    STRIPPED_CRIMSON_HYPHAE(BlockShape.CUBE),
    STRIPPED_CRIMSON_STEM(BlockShape.CUBE),
    STRIPPED_DARK_OAK_LOG(BlockShape.CUBE),
    STRIPPED_DARK_OAK_WOOD(BlockShape.CUBE),
    STRIPPED_JUNGLE_LOG(BlockShape.CUBE),
    STRIPPED_JUNGLE_WOOD(BlockShape.CUBE),
    STRIPPED_OAK_LOG(BlockShape.CUBE),
    STRIPPED_OAK_WOOD(BlockShape.CUBE),
    STRIPPED_SPRUCE_LOG(BlockShape.CUBE),
    STRIPPED_SPRUCE_WOOD(BlockShape.CUBE),
    STRIPPED_WARPED_HYPHAE(BlockShape.CUBE),
    STRIPPED_WARM_STEM(BlockShape.CUBE),
    STRUCTURE_BLOCK(BlockShape.CUBE),
    STRUCTURE_VOID(BlockShape.VOID),
    SUGAR_CANE(BlockShape.PLANT, Color.GREEN),
    SUNFLOWER(BlockShape.PLANT),
    SWEET_BERRY_BUSH(BlockShape.PLANT),
    TALL_GRASS(BlockShape.PLANT),
    TALL_SEAGRASS(BlockShape.PLANT),
    TARGET(BlockShape.CUBE),
    TERRACOTTA(BlockShape.CUBE),
    TINTED_GLASS(BlockShape.CUBE),
    TNT(BlockShape.CUBE, Color.RED),
    TORCH(BlockShape.STICK, Color.YELLOW),
    TRAPPED_CHEST(BlockShape.CUBE, Color.getHSBColor(0.11f, 1.0f, 0.4f)),
    TRIPWIRE(BlockShape.FLAT, Color.PINK),
    TRIPWIRE_HOOK(BlockShape.STICK, Color.LIGHT_GRAY),
    TUBE_CORAL(BlockShape.PLANT),
    TUBE_CORAL_BLOCK(BlockShape.CUBE),
    TUBE_CORAL_FAN(BlockShape.PLANT),
    TUBE_CORAL_WALL_FAN(BlockShape.PLANT),
    TUFF(BlockShape.CUBE),
    TURTLE_EGG(BlockShape.PLANT),
    TWISTING_VINES(BlockShape.PLANT),
    TWISTING_VINES_PLANT(BlockShape.PLANT),
    VINE(BlockShape.DOOR, Color.GREEN),
    VOID_AIR(BlockShape.VOID),
    WALL_TORCH(BlockShape.STICK),
    WARPED_BUTTON(BlockShape.SMALL),
    WARPED_DOOR(BlockShape.DOOR),
    WARPED_FENCE(BlockShape.FENCE),
    WARPED_FENCE_GATE(BlockShape.FENCE),
    WARPED_FUNGUS(BlockShape.PLANT),
    WARPED_HYPHAE(BlockShape.CUBE),
    WARPED_NYLIUM(BlockShape.CUBE),
    WARPED_PLANKS(BlockShape.CUBE),
    WARPED_PRESSURE_PLATE(BlockShape.FLAT),
    WARPED_ROOTS(BlockShape.PLANT),
    WARPED_SIGN(BlockShape.DOOR),
    WARPED_SLAB(BlockShape.SLAB),
    WARPED_STAIRS(BlockShape.STAIR),
    WARPED_STEM(BlockShape.CUBE),
    WARPED_TRAPDOOR(BlockShape.FLAT),
    WARPED_WALL_SIGN(BlockShape.DOOR),
    WARPED_WART_BLOCK(BlockShape.CUBE),
    WATER(BlockShape.CUBE, Color.BLUE),
    WATER_CAULDRON(BlockShape.CUBE),
    WAXED_COPPER_BLOCK(BlockShape.CUBE),
    WAXED_CUT_COPPER(BlockShape.CUBE),
    WAXED_CUT_COPPER_SLAB(BlockShape.SLAB),
    WAXED_CUT_COPPER_STAIRS(BlockShape.STAIR),
    WAXED_EXPOSED_COPPER(BlockShape.CUBE),
    WAXED_EXPOSED_CUT_COPPER(BlockShape.CUBE),
    WAXED_EXPOSED_CUT_COPPER_SLAB(BlockShape.SLAB),
    WAXED_EXPOSED_CUT_COPPER_STAIRS(BlockShape.STAIR),
    WAXED_OXIDIZED_COPPER(BlockShape.CUBE),
    WAXED_OXIDIZED_CUT_COPPER(BlockShape.CUBE),
    WAXED_OXIDIZED_CUT_COPPER_SLAB(BlockShape.SLAB),
    WAXED_OXIDIZED_CUT_COPPER_STAIRS(BlockShape.STAIR),
    WAXED_WEATHERED_COPPER(BlockShape.CUBE),
    WAXED_WEATHERED_CUT_COPPER(BlockShape.CUBE),
    WAXED_WEATHERED_CUT_COPPER_SLAB(BlockShape.SLAB),
    WAXED_WEATHERED_CUT_COPPER_STAIRS(BlockShape.STAIR),
    WEATHERED_COPPER(BlockShape.CUBE),
    WEATHERED_CUT_COPPER(BlockShape.CUBE),
    WEATHERED_CUT_COPPER_SLAB(BlockShape.SLAB),
    WEATHERED_CUT_COPPER_STAIRS(BlockShape.STAIR),
    WEEPING_VINES(BlockShape.PLANT),
    WEEPING_VINES_PLANT(BlockShape.PLANT),
    WET_SPONGE(BlockShape.CUBE),
    WHEAT(BlockShape.PLANT),
    WHITE_BANNER(BlockShape.DOOR),
    WHITE_BED(BlockShape.SLAB),
    WHITE_CANDLE(BlockShape.PLANT),
    WHITE_CANDLE_CAKE(BlockShape.SLAB),
    WHITE_CARPET(BlockShape.FLAT),
    WHITE_CONCRETE(BlockShape.CUBE),
    WHITE_CONCRETE_POWDER(BlockShape.CUBE),
    WHITE_GLAZED_TERRACOTTA(BlockShape.CUBE),
    WHITE_SHULKER_BOX(BlockShape.CUBE),
    WHITE_STAINED_GLASS(BlockShape.CUBE),
    WHITE_STAINED_GLASS_PANE(BlockShape.FENCE),
    WHITE_TERRACOTTA(BlockShape.CUBE),
    WHITE_TULIP(BlockShape.PLANT),
    WHITE_WALL_BANNER(BlockShape.DOOR),
    WHITE_WOOL(BlockShape.CUBE),
    WITHER_ROSE(BlockShape.PLANT),
    WITHER_SKELETON_SKULL(BlockShape.SMALL),
    WITHER_SKELETON_WALL_SKULL(BlockShape.SMALL),
    YELLOW_BANNER(BlockShape.DOOR),
    YELLOW_BED(BlockShape.SLAB),
    YELLOW_CANDLE(BlockShape.PLANT),
    YELLOW_CANDLE_CAKE(BlockShape.SLAB),
    YELLOW_CARPET(BlockShape.FLAT),
    YELLOW_CONCRETE(BlockShape.CUBE),
    YELLOW_CONCRETE_POWDER(BlockShape.CUBE),
    YELLOW_GLAZED_TERRACOTTA(BlockShape.CUBE),
    YELLOW_SHULKER_BOX(BlockShape.CUBE),
    YELLOW_STAINED_GLASS(BlockShape.CUBE),
    YELLOW_STAINED_GLASS_PANE(BlockShape.FLAT),
    YELLOW_TERRACOTTA(BlockShape.CUBE),
    YELLOW_WALL_BANNER(BlockShape.DOOR),
    YELLOW_WOOL(BlockShape.CUBE),
    ZOMBIE_HEAD(BlockShape.SMALL),
    ZOMBIE_WALL_HEAD(BlockShape.SMALL);

    private final Color color;
    private final BlockShape blockShape;

    Material(BlockShape blockShape, Color color) {
        this.color = color;
        this.blockShape = blockShape;
    }

    Material(BlockShape blockShape) {
        color = Color.BLACK;
        this.blockShape = blockShape;
    }

    static String[] strings() {
        String[] materialNames = new String[values().length];
        int i = 0;
        for (Material material : values()) {
            materialNames[i] = material.toString();
            i++;
        }
        return materialNames;
    }

    /**
     * Gets the Color of this Material
     *
     * @return Color of this material
     */
    public Color getColor() {
        return color;
    }

    /**
     * Gets the BlockShape of this Material
     *
     * @return BlockShape of this material
     */
    public BlockShape getBlockShape() {
        return blockShape;
    }

    /**
     * Gets whether this material is glass.
     *
     * @return true if the material is glass
     */
    public boolean isGlass() {
        return switch (this) {
            case GLASS, GREEN_STAINED_GLASS, GREEN_STAINED_GLASS_PANE, GLASS_PANE -> true;
            default -> false;
        };
    }
}
